# Generated by Django 4.2.2 on 2023-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('web', 'Web'), ('stock', 'Stock'), ('membre', 'Membre')], default='membre', max_length=20),
        ),
    ]
